POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Jo",
    "number": "1234567890"
}

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/68aa2b2438016673e366404f