GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "VS Code Rest client is a pretty handy tool",
    "important": true,
    "userId": "68aeb842e26095a86930b6e5"
}

###
POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "lol",
    "important": true
}